version: "3.8"
services:
  postgres:
    image: postgis/postgis:14-3.2-alpine
    volumes: 
      - ./storage/postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=C7yYPlzTPhBb8GqLTosj
      - POSTGRES_DB=ncs_vurn
      - POSTGRES_PORT=5432
    dns:
      - "8.8.8.8" 
      - "8.8.4.4"
      - "127.0.0.11"
    expose:
      - 5432

  redis:
    image: redis
    volumes: 
      - ./storage/redis-data:/var/lib/redis
    environment:
      - REDIS_APPLICATION_MODE=master
    dns:
      - "8.8.8.8" 
      - "8.8.4.4"
      - "127.0.0.11"
  
  fastapi:
    build: ./fastapi
    command: >
      sh -c "cd proj 
      && ./start.sh"
    volumes:
      - ./fastapi:/proj
    ports:
      - "8080:8080"
    dns:
      - "8.8.8.8" 
      - "8.8.4.4"
      - "127.0.0.11"
    environment:
      - HOME=/proj
    env_file:
      - ./fastapi/.env
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_started
  
  sveltekit:
    build: ./sveltekit
    ports:
      - 5173:5173
    volumes:
      - ./sveltekit:/app:Z
    environment:
      - VITE_BACKEND_URL=http://localhost:8080
